openapi: 3.0.1
info:
  title: 'SLS'
  version: 1.0.0
paths:
  '/users': 
    get:
      operationId: getUser
      responses:
        '200':
          description: ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
                
    parameters:
      - name: userId
        in: query
        schema:
          type: integer
      - name: phoneNumber
        in: query
        schema:
          type: string
    
    post:
      operationId: postUser
      responses:
        '200':
          description: ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
                
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                phoneNumber:
                  type: string
                  description: phone number
                fname:
                  type: string
                  description: fname
                lname:
                  type: string
                  description: lname

    

    patch:
      operationId: patchUser
      responses:
        '200':
          description: ok
          content: 
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'
        
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/User'
                
    
    delete:
      operationId: deleteUser
      responses: 
        '200':
          description: ok
      parameters:
      - name: userId
        in: query
        schema:
          type: integer
      - name: phoneNumber
        in: query
        schema:
          type: string
      - name: userIds
        in: query
        schema:
          type: array
    
  
components:
  schemas:
    User:
      title: user
      type: object
      description: ''
      properties:
        userId:
          type: integer
          description: userId
        phoneNumber:
          type: string
          description: phone number
        fname:
          type: string
          description: fname
        lname:
          type: string
          description: lname